name: Test
on: [push]

jobs:
  validate:
    name: Validate map integrity
    runs-on: ubuntu-latest
    container:
      image: golang:1.13-alpine3.10
    steps:
      - run: apk add --no-cache git
      - uses: actions/checkout@v1
      - run: go mod download
      - run: go run .
