name: Test
on: [push]

jobs:
  validate:
    name: Validate map integrity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - run: go get
      - run: go run validate.go
